base:
- systemd
- linux-image-amd64
- initramfs-tools
- grub-efi-amd64-bin
- grub-efi-amd64-signed
- shim-signed
- grub2-common
- gdisk
- dosfstools
- e2fsprogs
- squashfs-tools
- parted
- ca-certificates
- apt
- iproute2
- iputils-ping
- locales
- keyboard-configuration
- console-setup
- console-setup-linux
- tzdata
- openssh-server
- sudo
- nftables
- apparmor
- apparmor-utils
- systemd-zram-generator
graphical:
- libwayland-client0
- libwayland-egl1
- libx11-6
- libxkbcommon0
- libinput10
- libgtk-4-1
- librsvg2-common
- mesa-utils
- mesa-vulkan-drivers
- fonts-dejavu-core
- adwaita-icon-theme
- adwaita-icon-theme-legacy
- hicolor-icon-theme
- alsa-utils
- pipewire
- pipewire-alsa
- wireplumber
- usbutils
- pcscd
- libccid
- cups-client
xaac: []
optional: []
exclude:
- task-desktop
- task-gnome-desktop
- task-kde-desktop
- foot
- gnome-terminal
- konsole
- mate-terminal
- rxvt-unicode
- tilix
- weston
- xfce4-terminal
- xterm
