"""Safe build workspace management for XAAC Thin Client OS."""

from __future__ import annotations

import json
import os
import shutil
import socket
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from secrets import token_hex
from typing import Any


class WorkspaceError(RuntimeError):
    """Base error for workspace operations."""


class WorkspaceLockedError(WorkspaceError):
    """Raised when another process owns the workspace lock."""


@dataclass(frozen=True, slots=True)
class BuildWorkspace:
    """Paths and metadata for one isolated build run."""

    root: Path
    build_root: Path
    run_dir: Path
    build_id: str
    manifest_path: Path

    @property
    def logs_dir(self) -> Path:
        return self.run_dir / "logs"

    @property
    def artifacts_dir(self) -> Path:
        return self.run_dir / "artifacts"

    @property
    def temporary_dir(self) -> Path:
        return self.run_dir / "tmp"

    @property
    def rendered_dir(self) -> Path:
        return self.run_dir / "rendered"

    @property
    def rootfs_dir(self) -> Path:
        """Root filesystem generated by debootstrap for this run."""
        return self.run_dir / "rootfs"


class WorkspaceManager:
    """Create, lock, inspect and clean project build workspaces."""

    def __init__(self, project_root: Path) -> None:
        self.project_root = project_root.resolve()
        self.build_root = self.project_root / ".build"
        self.runs_root = self.build_root / "runs"
        self.lock_path = self.build_root / ".lock"
        self.current_path = self.build_root / "current"
        self._lock_fd: int | None = None

    def _assert_safe_build_root(self) -> None:
        expected = self.project_root / ".build"
        if self.build_root != expected or self.build_root == Path("/"):
            raise WorkspaceError("Ruta .build insegura")

    def acquire_lock(self) -> None:
        """Acquire an exclusive lock represented by an atomically created file."""
        self._assert_safe_build_root()
        self.build_root.mkdir(parents=True, exist_ok=True)
        payload = {
            "pid": os.getpid(),
            "host": socket.gethostname(),
            "created_at": datetime.now(UTC).isoformat(),
        }
        try:
            fd = os.open(self.lock_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        except FileExistsError as exc:
            owner = self.read_lock()
            detail = f" ({owner})" if owner else ""
            raise WorkspaceLockedError(f"L'espai de treball ja està bloquejat{detail}") from exc
        os.write(fd, json.dumps(payload, sort_keys=True).encode("utf-8"))
        os.fsync(fd)
        self._lock_fd = fd

    def release_lock(self) -> None:
        """Release a lock owned by this manager instance."""
        if self._lock_fd is None:
            return
        os.close(self._lock_fd)
        self._lock_fd = None
        self.lock_path.unlink(missing_ok=True)

    def read_lock(self) -> dict[str, Any] | None:
        """Return lock owner metadata when available."""
        try:
            data = json.loads(self.lock_path.read_text(encoding="utf-8"))
        except (FileNotFoundError, json.JSONDecodeError, OSError):
            return None
        return data if isinstance(data, dict) else None

    def __enter__(self) -> WorkspaceManager:
        self.acquire_lock()
        return self

    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None:
        self.release_lock()

    @staticmethod
    def create_build_id(now: datetime | None = None) -> str:
        """Create a sortable, collision-resistant build identifier."""
        instant = now or datetime.now(UTC)
        return f"{instant:%Y%m%dT%H%M%SZ}-{token_hex(4)}"

    def prepare(self, manifest: dict[str, Any]) -> BuildWorkspace:
        """Create an isolated run directory and its initial manifest."""
        if self._lock_fd is None:
            raise WorkspaceError("Cal adquirir el bloqueig abans de preparar la construcció")
        build_id = self.create_build_id()
        run_dir = self.runs_root / build_id
        run_dir.mkdir(parents=True, mode=0o750)
        for child in ("logs", "artifacts", "tmp", "rendered"):
            (run_dir / child).mkdir(mode=0o750)

        manifest_path = run_dir / "manifest.json"
        complete_manifest = {
            **manifest,
            "build_id": build_id,
            "created_at": datetime.now(UTC).isoformat(),
            "status": "prepared",
            "workspace": str(run_dir.relative_to(self.project_root)),
        }
        self._write_json_atomic(manifest_path, complete_manifest)
        self._set_current(build_id)
        return BuildWorkspace(
            root=self.project_root,
            build_root=self.build_root,
            run_dir=run_dir,
            build_id=build_id,
            manifest_path=manifest_path,
        )

    def _set_current(self, build_id: str) -> None:
        temporary = self.build_root / ".current.tmp"
        temporary.write_text(f"{build_id}\n", encoding="utf-8")
        temporary.replace(self.current_path)

    @staticmethod
    def _write_json_atomic(path: Path, payload: dict[str, Any]) -> None:
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        temporary.replace(path)

    def current(self) -> BuildWorkspace | None:
        """Return the latest prepared workspace, if it is valid."""
        try:
            build_id = self.current_path.read_text(encoding="utf-8").strip()
        except OSError:
            return None
        if not build_id or "/" in build_id or "\\" in build_id:
            return None
        run_dir = self.runs_root / build_id
        manifest_path = run_dir / "manifest.json"
        if not run_dir.is_dir() or not manifest_path.is_file():
            return None
        return BuildWorkspace(
            root=self.project_root,
            build_root=self.build_root,
            run_dir=run_dir,
            build_id=build_id,
            manifest_path=manifest_path,
        )

    def clean(self) -> bool:
        """Remove the complete build workspace after strict path validation."""
        self._assert_safe_build_root()
        if not self.build_root.exists():
            return False
        if self._lock_fd is not None or self.lock_path.exists():
            raise WorkspaceLockedError("No es pot netejar un espai de treball bloquejat")
        shutil.rmtree(self.build_root)
        return True
